language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t brinkers/react-test -f ./client/Dockerfile.dev   ./client


script:
  - docker run -e CI=true brinkers/react-test npm test
  

after_success:
  - docker build -t brinkers/multi-client ./client
  - docker build -t brinkers/multi-nginx ./nginx
  - docker build -t brinkers/multi-server ./server
  - docker build -t brinkers/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  - docker push brinkers/multi-client
  - docker push brinkers/multi-nginx
  - docker push brinkers/multi-server
  - docker push brinkers/multi-worker
